name = "catering-app"
compatibility_date = "2023-12-01"
main = "functions/index.ts"

[env.production]
account_id = "f02feae0cf0a84543999af688f33a7bf"
name = "catering-app-production"

[[d1_databases]]
binding = "DB"
database_name = "catering_db"
database_id = "10d6dc18-7d6d-48da-a20c-6e70ed999194"
migrations_dir = "./migrations"

[vars]
NODE_ENV = "production"