name = "catering-app"
compatibility_date = "2023-12-01"
main = "functions/index.ts"

[env.production]
account_id = "2f85aafa98f3148b77205259e5d59ce6"
name = "catering-app-production"
routes = ["catering.hijrah-attauhid.or.id/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "catering-app-db"
database_id = "a35d5ff1-b8fa-46c0-95c7-5bdce7d61c57"
migrations_dir = "./migrations"

[env.production.vars]
NODE_ENV = "production"